/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 background.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
  const { nodes, materials } = useGLTF('/background.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials['Materiał.001']} position={[-4.478, 0.064, -0.835]} rotation={[3.091, 0.083, -3.054]} scale={0.3} />
      <mesh geometry={nodes['5'].geometry} material={materials['Materiał.002']} position={[-5.771, 0.064, -1.017]} rotation={[Math.PI / 2, 0, -0.609]} scale={0.44} />
      <mesh geometry={nodes['4'].geometry} material={materials['Materiał.004']} position={[-3.909, 0.064, -1.587]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['1'].geometry} material={materials['Materiał.001']} position={[-3.416, 0.064, -1.37]} rotation={[3.091, 0.083, -3.054]} scale={0.3} />
      <mesh geometry={nodes['3'].geometry} material={materials['Materiał.005']} position={[-4.427, 0.064, -2.074]} rotation={[Math.PI / 2, 0, 0.258]} scale={0.3} />
      <mesh geometry={nodes['5001'].geometry} material={materials['Materiał.007']} position={[-4.433, 0.064, -2.691]} rotation={[Math.PI / 2, 0, -0.381]} scale={0.44} />
      <mesh geometry={nodes['4001'].geometry} material={materials['Materiał.006']} position={[-2.49, 0.064, -2.824]} rotation={[2.761, -0.132, -3.111]} scale={0.069} />
      <mesh geometry={nodes['3001'].geometry} material={materials['Materiał.003']} position={[-2.885, 0.064, -3.415]} rotation={[Math.PI / 2, 0, 0.486]} scale={0.3} />
      <mesh geometry={nodes['2001'].geometry} material={materials['Materiał.008']} position={[-3.215, 0.064, -2.22]} rotation={[3.089, 0.311, -3.042]} scale={0.3} />
      <mesh geometry={nodes['1001'].geometry} material={materials['Materiał.008']} position={[-2.06, 0.064, -2.501]} rotation={[3.089, 0.311, -3.042]} scale={0.3} />
      <mesh geometry={nodes['5002'].geometry} material={materials['Materiał.009']} position={[-2.401, 0.064, -4.053]} rotation={[Math.PI / 2, 0, 0.287]} scale={0.44} />
      <mesh geometry={nodes['4002'].geometry} material={materials['Materiał.010']} position={[-0.793, 0.064, -2.954]} rotation={[2.712, 0.486, -2.848]} scale={0.069} />
      <mesh geometry={nodes['3002'].geometry} material={materials['Materiał.011']} position={[-0.736, 0.064, -3.663]} rotation={[Math.PI / 2, 0, 1.154]} scale={0.3} />
      <mesh geometry={nodes['2002'].geometry} material={materials['Materiał.012']} position={[-1.735, 0.064, -2.929]} rotation={[3.052, 0.978, -2.984]} scale={0.3} />
      <mesh geometry={nodes['1002'].geometry} material={materials['Materiał.012']} position={[-0.654, 0.064, -2.435]} rotation={[3.052, 0.978, -2.984]} scale={0.3} />
      <mesh geometry={nodes['5003'].geometry} material={materials['Materiał.014']} position={[-0.27, 0.064, -4.539]} rotation={[Math.PI / 2, 0, 0.66]} scale={0.44} />
      <mesh geometry={nodes['4003'].geometry} material={materials['Materiał.015']} position={[0.827, 0.064, -2.93]} rotation={[2.575, 0.815, -2.625]} scale={0.069} />
      <mesh geometry={nodes['3003'].geometry} material={materials['Materiał.016']} position={[1.138, 0.064, -3.57]} rotation={[Math.PI / 2, 0, 1.527]} scale={0.3} />
      <mesh geometry={nodes['2003'].geometry} material={materials['Materiał.013']} position={[-0.06, 0.064, -3.25]} rotation={[2.914, 1.347, -2.836]} scale={0.3} />
      <mesh geometry={nodes['1003'].geometry} material={materials['Materiał.013']} position={[0.767, 0.064, -2.396]} rotation={[2.914, 1.347, -2.836]} scale={0.3} />
      <mesh geometry={nodes['5004'].geometry} material={materials['Materiał.017']} position={[2.233, 0.064, -4.147]} rotation={[Math.PI / 2, 0, 1.227]} scale={0.44} />
      <mesh geometry={nodes['4004'].geometry} material={materials['Materiał.018']} position={[2.293, 0.064, -2.201]} rotation={[1.828, 1.18, -1.764]} scale={0.069} />
      <mesh geometry={nodes['3004'].geometry} material={materials['Materiał.019']} position={[2.899, 0.064, -2.573]} rotation={[Math.PI / 2, 0, 2.094]} scale={0.3} />
      <mesh geometry={nodes['2004'].geometry} material={materials['Materiał.020']} position={[1.717, 0.064, -2.948]} rotation={[0.146, 1.218, -0.054]} scale={0.3} />
      <mesh geometry={nodes['1004'].geometry} material={materials['Materiał.020']} position={[1.955, 0.064, -1.783]} rotation={[0.146, 1.218, -0.054]} scale={0.3} />
      <mesh geometry={nodes['5005'].geometry} material={materials['Materiał.021']} position={[3.736, 0.064, -4.115]} rotation={[Math.PI / 2, 0, 1.002]} scale={0.44} />
      <mesh geometry={nodes['4005'].geometry} material={materials['Materiał.022']} position={[4.229, 0.064, -2.231]} rotation={[2.256, 1.076, -2.236]} scale={0.069} />
      <mesh geometry={nodes['3005'].geometry} material={materials['Materiał.023']} position={[4.737, 0.064, -2.729]} rotation={[Math.PI / 2, 0, 1.869]} scale={0.3} />
      <mesh geometry={nodes['2005'].geometry} material={materials['Materiał.024']} position={[3.501, 0.064, -2.83]} rotation={[0.386, 1.437, -0.299]} scale={0.3} />
      <mesh geometry={nodes['1005'].geometry} material={materials['Materiał.024']} position={[3.993, 0.064, -1.747]} rotation={[0.386, 1.437, -0.299]} scale={0.3} />
      <mesh geometry={nodes['5006'].geometry} material={materials['Materiał.025']} position={[5.159, 0.064, -1.896]} rotation={[Math.PI / 2, 0, 1.574]} scale={0.44} />
      <mesh geometry={nodes['4006'].geometry} material={materials['Materiał.026']} position={[4.555, 0.064, -0.044]} rotation={[1.027, 1.126, -0.897]} scale={0.069} />
      <mesh geometry={nodes['3006'].geometry} material={materials['Materiał.027']} position={[5.252, 0.064, -0.189]} rotation={[Math.PI / 2, 0, 2.44]} scale={0.3} />
      <mesh geometry={nodes['2006'].geometry} material={materials['Materiał.028']} position={[4.267, 0.064, -0.942]} rotation={[0.078, 0.874, 0.023]} scale={0.3} />
      <mesh geometry={nodes['1006'].geometry} material={materials['Materiał.028']} position={[4.095, 0.064, 0.235]} rotation={[0.078, 0.874, 0.023]} scale={0.3} />
      <mesh geometry={nodes['5007'].geometry} material={materials['Materiał.029']} position={[-5.221, 0.064, 2.004]} rotation={[Math.PI / 2, 0, -1.594]} scale={0.44} />
      <mesh geometry={nodes['5008'].geometry} material={materials['Materiał.030']} position={[-3.741, 0.064, 4.186]} rotation={[Math.PI / 2, 0, -2.165]} scale={0.44} />
      <mesh geometry={nodes['5009'].geometry} material={materials['Materiał.031']} position={[-2.238, 0.064, 4.18]} rotation={[Math.PI / 2, 0, -1.94]} scale={0.44} />
      <mesh geometry={nodes['5010'].geometry} material={materials['Materiał.032']} position={[0.275, 0.064, 4.507]} rotation={[Math.PI / 2, 0, -2.508]} scale={0.44} />
      <mesh geometry={nodes['5011'].geometry} material={materials['Materiał.033']} position={[2.392, 0.064, 3.967]} rotation={[Math.PI / 2, 0, -2.88]} scale={0.44} />
      <mesh geometry={nodes['5012'].geometry} material={materials['Materiał.034']} position={[4.389, 0.064, 2.553]} rotation={[Math.PI / 2, 0, 2.735]} scale={0.44} />
      <mesh geometry={nodes['5013'].geometry} material={materials['Materiał.035']} position={[5.683, 0.064, 0.845]} rotation={[Math.PI / 2, 0, 2.507]} scale={0.44} />
      <mesh geometry={nodes['4007'].geometry} material={materials['Materiał.036']} position={[-4.665, 0.064, 0.138]} rotation={[2.067, -1.139, 2.192]} scale={0.069} />
      <mesh geometry={nodes['4008'].geometry} material={materials['Materiał.037']} position={[-4.282, 0.064, 2.315]} rotation={[0.85, -1.059, 0.865]} scale={0.069} />
      <mesh geometry={nodes['4009'].geometry} material={materials['Materiał.038']} position={[-2.348, 0.064, 2.236]} rotation={[1.254, -1.173, 1.313]} scale={0.069} />
      <mesh geometry={nodes['4010'].geometry} material={materials['Materiał.039']} position={[-0.864, 0.064, 2.927]} rotation={[0.552, -0.793, 0.497]} scale={0.069} />
      <mesh geometry={nodes['4011'].geometry} material={materials['Materiał.040']} position={[0.756, 0.064, 2.909]} rotation={[0.424, -0.462, 0.282]} scale={0.069} />
      <mesh geometry={nodes['4012'].geometry} material={materials['Materiał.041']} position={[2.45, 0.064, 2.735]} rotation={[0.382, 0.155, 0.021]} scale={0.069} />
      <mesh geometry={nodes['4013'].geometry} material={materials['Materiał.042']} position={[3.836, 0.064, 1.462]} rotation={[0.405, 0.366, -0.069]} scale={0.069} />
      <mesh geometry={nodes['3007'].geometry} material={materials['Materiał.043']} position={[-5.357, 0.064, 0.3]} rotation={[Math.PI / 2, 0, -0.727]} scale={0.3} />
      <mesh geometry={nodes['3008'].geometry} material={materials['Materiał.044']} position={[-4.777, 0.064, 2.826]} rotation={[Math.PI / 2, 0, -1.298]} scale={0.3} />
      <mesh geometry={nodes['3009'].geometry} material={materials['Materiał.045']} position={[-2.944, 0.064, 2.623]} rotation={[Math.PI / 2, 0, -1.073]} scale={0.3} />
      <mesh geometry={nodes['3010'].geometry} material={materials['Materiał.046']} position={[-1.158, 0.064, 3.574]} rotation={[Math.PI / 2, 0, -1.641]} scale={0.3} />
      <mesh geometry={nodes['3011'].geometry} material={materials['Materiał.047']} position={[0.718, 0.064, 3.62]} rotation={[Math.PI / 2, 0, -2.013]} scale={0.3} />
      <mesh geometry={nodes['3012'].geometry} material={materials['Materiał.048']} position={[2.86, 0.064, 3.317]} rotation={[Math.PI / 2, 0, -2.681]} scale={0.3} />
      <mesh geometry={nodes['3013'].geometry} material={materials['Materiał.049']} position={[4.367, 0.064, 1.936]} rotation={[Math.PI / 2, 0, -2.909]} scale={0.3} />
      <mesh geometry={nodes['2007'].geometry} material={materials['Materiał.050']} position={[-4.353, 0.064, 1.028]} rotation={[3.061, -0.9, -3.122]} scale={0.3} />
      <mesh geometry={nodes['2008'].geometry} material={materials['Materiał.051']} position={[-3.539, 0.064, 2.896]} rotation={[2.669, -1.46, 2.754]} scale={0.3} />
      <mesh geometry={nodes['2009'].geometry} material={materials['Materiał.052']} position={[-1.753, 0.064, 2.967]} rotation={[2.985, -1.244, 3.076]} scale={0.3} />
      <mesh geometry={nodes['2010'].geometry} material={materials['Materiał.053']} position={[0.031, 0.064, 3.224]} rotation={[0.205, -1.321, 0.282]} scale={0.3} />
      <mesh geometry={nodes['2011'].geometry} material={materials['Materiał.054']} position={[1.698, 0.064, 2.86]} rotation={[0.087, -0.952, 0.154]} scale={0.3} />
      <mesh geometry={nodes['2012'].geometry} material={materials['Materiał.055']} position={[3.159, 0.064, 2.114]} rotation={[0.052, -0.286, 0.098]} scale={0.3} />
      <mesh geometry={nodes['2013'].geometry} material={materials['Materiał.056']} position={[4.386, 0.064, 0.696]} rotation={[0.05, -0.058, 0.086]} scale={0.3} />
      <mesh geometry={nodes['1007'].geometry} material={materials['Materiał.050']} position={[-4.212, 0.064, -0.153]} rotation={[3.061, -0.9, -3.122]} scale={0.3} />
      <mesh geometry={nodes['1008'].geometry} material={materials['Materiał.051']} position={[-4.059, 0.064, 1.826]} rotation={[2.669, -1.46, 2.754]} scale={0.3} />
      <mesh geometry={nodes['1009'].geometry} material={materials['Materiał.052']} position={[-2.021, 0.064, 1.809]} rotation={[2.985, -1.244, 3.076]} scale={0.3} />
      <mesh geometry={nodes['1010'].geometry} material={materials['Materiał.053']} position={[-0.818, 0.064, 2.391]} rotation={[0.205, -1.321, 0.282]} scale={0.3} />
      <mesh geometry={nodes['1011'].geometry} material={materials['Materiał.054']} position={[0.604, 0.064, 2.394]} rotation={[0.087, -0.952, 0.154]} scale={0.3} />
      <mesh geometry={nodes['1012'].geometry} material={materials['Materiał.055']} position={[2.011, 0.064, 2.424]} rotation={[0.052, -0.286, 0.098]} scale={0.3} />
      <mesh geometry={nodes['1013'].geometry} material={materials['Materiał.056']} position={[3.338, 0.064, 1.259]} rotation={[0.05, -0.058, 0.086]} scale={0.3} />
      <mesh geometry={nodes['3A002'].geometry} material={materials['Materiał.058']} position={[3.183, -0.29, 0.797]} rotation={[Math.PI / 2, 0, 0.258]} scale={0.3} />
      <mesh geometry={nodes['3A003'].geometry} material={materials['Materiał.059']} position={[3.234, 0.123, -1.695]} rotation={[Math.PI / 2, 0, 0.258]} scale={0.3} />
      <mesh geometry={nodes['3A007'].geometry} material={materials['Materiał.063']} position={[2.792, 0.064, 1.368]} rotation={[Math.PI / 2, 0, 0.258]} scale={0.3} />
      <mesh geometry={nodes['5A001'].geometry} material={materials['Materiał.065']} position={[5.878, 0.636, -0.178]} rotation={[Math.PI / 2, 0, -1.588]} scale={0.3} />
      <mesh geometry={nodes['5A002'].geometry} material={materials['Materiał.066']} position={[5.132, 0.723, -2.962]} rotation={[Math.PI / 2, 0, -1.968]} scale={0.3} />
      <mesh geometry={nodes['5A003'].geometry} material={materials['Materiał.067']} position={[5.132, 0.723, -3.32]} rotation={[Math.PI / 2, 0, -1.968]} scale={0.3} />
      <mesh geometry={nodes['5A004'].geometry} material={materials['Materiał.068']} position={[-3.341, 0.723, -3.679]} rotation={[Math.PI / 2, 0, 2.652]} scale={0.3} />
      <mesh geometry={nodes['5A005'].geometry} material={materials['Materiał.069']} position={[-1.15, 0.723, -4.333]} rotation={[Math.PI / 2, 0, -2.962]} scale={0.3} />
      <mesh geometry={nodes['5A006'].geometry} material={materials['Materiał.070']} position={[-0.89, 0.723, -4.333]} rotation={[Math.PI / 2, 0, -2.962]} scale={0.3} />
      <mesh geometry={nodes['5A007'].geometry} material={materials['Materiał.071']} position={[1.467, 0.723, -4.333]} rotation={[Math.PI / 2, 0, -2.962]} scale={0.3} />
      <mesh geometry={nodes['5A008'].geometry} material={materials['Materiał.072']} position={[1.467, 0.723, -4.333]} rotation={[Math.PI / 2, 0, -2.962]} scale={0.3} />
      <mesh geometry={nodes['5A009'].geometry} material={materials['Materiał.073']} position={[-5.409, 0.636, -2.216]} rotation={[Math.PI / 2, 0, -0.75]} scale={0.3} />
      <mesh geometry={nodes['5A010'].geometry} material={materials['Materiał.074']} position={[-5.409, 0.636, -1.888]} rotation={[Math.PI / 2, 0, -0.75]} scale={0.3} />
      <mesh geometry={nodes['5A011'].geometry} material={materials['Materiał.075']} position={[-5.915, 0.636, 0.166]} rotation={[Math.PI / 2, 0, -1.734]} scale={0.3} />
      <mesh geometry={nodes['5A012'].geometry} material={materials['Materiał.076']} position={[-5.915, 0.636, 1.046]} rotation={[Math.PI / 2, 0, -1.734]} scale={0.3} />
      <mesh geometry={nodes['5A013'].geometry} material={materials['Materiał.077']} position={[-5.34, 0.924, 2.67]} rotation={[Math.PI / 2, 0, -2.119]} scale={0.3} />
      <mesh geometry={nodes['5A014'].geometry} material={materials['Materiał.078']} position={[-4.926, 0.924, 3.003]} rotation={[Math.PI / 2, 0, -2.119]} scale={0.3} />
      <mesh geometry={nodes['5A015'].geometry} material={materials['Materiał.079']} position={[-1.388, 0.924, 4.353]} rotation={[Math.PI / 2, 0, 3.025]} scale={0.3} />
      <mesh geometry={nodes['5A016'].geometry} material={materials['Materiał.080']} position={[-1.007, 0.522, 4.682]} rotation={[Math.PI / 2, 0, 3.025]} scale={0.3} />
      <mesh geometry={nodes['5A'].geometry} material={materials['Materiał.002']} position={[5.878, 0.636, 0.325]} rotation={[Math.PI / 2, 0, -1.469]} scale={0.3} />
      <mesh geometry={nodes['1A'].geometry} material={materials['Materiał.001']} position={[4.53, 0.064, 0.353]} rotation={[3.091, 0.083, -3.054]} scale={0.3} />
      <mesh geometry={nodes['4A'].geometry} material={materials['Materiał.004']} position={[-2.849, 0.064, 1.309]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['2A'].geometry} material={materials['Materiał.001']} position={[6.93, 0.003, 0.353]} rotation={[3.091, 0.083, -3.054]} scale={0.3} />
      <mesh geometry={nodes['5A017'].geometry} material={materials['Materiał.081']} position={[-1.388, 0.924, 4.353]} rotation={[Math.PI / 2, 0, 3.025]} scale={0.3} />
      <mesh geometry={nodes['4A001'].geometry} material={materials['Materiał.082']} position={[2.103, 0.064, 1.083]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A002'].geometry} material={materials['Materiał.083']} position={[-3.037, 0.064, 0.353]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A003'].geometry} material={materials['Materiał.084']} position={[2.819, 0.064, 0.353]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A004'].geometry} material={materials['Materiał.085']} position={[-2.919, 0.064, -0.739]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A005'].geometry} material={materials['Materiał.086']} position={[0.597, 0.064, -1.932]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A006'].geometry} material={materials['Materiał.087']} position={[1.525, 0.064, -1.509]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes['4A007'].geometry} material={materials['Materiał.088']} position={[-2.16, 0.064, -1.201]} rotation={[2.74, -0.343, 3.083]} scale={0.069} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0.022, 0.013, 0.026]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.862, -1.01, -0.647]} />
    </group>
  )
}

useGLTF.preload('/background.glb')
