/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 forest_demo.glb 
Author: patrix (https://sketchfab.com/patrix)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/forest-demo-1269b7e00f9d4ce09931c0c95967bc33
Title: Forest Demo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Forest(props) {
  const { nodes, materials } = useGLTF('forest_demo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.forest_forest_0.geometry} material={materials.forest} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('forest_demo.glb')
